// Auto-generated by Rusty Refactor (SRP)
// Responsibility: Implement core logic for SRP refactoring in Rust and TypeScript

import * as path from 'path';
import * as vscode from 'vscode';
import { RustAnalyzerIntegration } from '../../rustAnalyzerIntegration';
import { AnalyzeRustCodeTool } from '../../AnalyzeRustCodeTool';
import { ExtractToModuleTool } from '../../ExtractToModuleTool';
import { logToOutput } from '../../extractor';
import { suggestImportsForTypes } from '../../nativeBridge';
import { Utils } from '../../utils';
import { UnifiedModelClient, ChatMessage } from '../../codetetherClient';
import {
    ISrpRefactorParameters,
    SrpGroup,
    SrpPlan,
    SrpStep,
    TsTopLevelSymbol
} from '../srp_interfaces/srp_interfaces';

export class SrpRefactorTool implements vscode.LanguageModelTool<ISrpRefactorParameters> {
    private analyzeTool: AnalyzeRustCodeTool;
    private extractTool: ExtractToModuleTool;
    private modelClient: UnifiedModelClient;

    constructor(private rustAnalyzer: RustAnalyzerIntegration) {
        this.analyzeTool = new AnalyzeRustCodeTool(rustAnalyzer);
        this.extractTool = new ExtractToModuleTool(rustAnalyzer);
        this.modelClient = new UnifiedModelClient();
    }

    async prepareInvocation(
        options: vscode.LanguageModelToolInvocationPrepareOptions<ISrpRefactorParameters>,
        _token: vscode.CancellationToken
    ): Promise<vscode.PreparedToolInvocation> {
        const params = options.input;
        const fileName = params.filePath.split(/[\\/]/).pop() || 'file';
        const maxLines = params.maxLinesPerModule || 50;

        return {
            invocationMessage: `Refactoring ${fileName} to SRP modules (≤${maxLines} lines each)...`,
            confirmationMessages: {
                title: 'SRP Modular Refactor',
                message: new vscode.MarkdownString(
                    `Refactor **${fileName}** into SRP-compliant modules?\n\n` +
                    `This will:\n` +
                    `- Analyze top-level symbols\n` +
                    `- Use an LLM to group symbols by single responsibility\n` +
                    `- Extract groups to focused modules (≤**${maxLines}** lines)\n` +
                    `- Keep module cohesion and improve maintainability\n\n` +
                    `${params.targetDirectory ? `**Target:** ${params.targetDirectory}/\n` : ''}`
                ),
            },
        };
    }

    async invoke(
        options: vscode.LanguageModelToolInvocationOptions<ISrpRefactorParameters>,
        _token: vscode.CancellationToken
    ): Promise<vscode.LanguageModelToolResult> {
        const params = options.input;

        try {
            const uri = vscode.Uri.file(params.filePath);
            const document = await vscode.workspace.openTextDocument(uri);

            if (document.languageId === 'rust') {
                return this.invokeRust(params, document, _token);
            }

            if (this.isTypeScriptLanguage(document.languageId)) {
                return this.invokeTypeScript(params, document, _token);
            }

            throw new Error(`Unsupported language: ${document.languageId}. SRP refactor currently supports Rust and TypeScript.`);
        } catch (error) {
            const msg = error instanceof Error ? error.message : String(error);
            return new vscode.LanguageModelToolResult([
                new vscode.LanguageModelTextPart(`❌ SRP refactor failed: ${msg}`)
            ]);
        }
    }

    // ========================================================================
    // Rust flow (existing behavior, preserved)
    // ========================================================================

    private async invokeRust(
        params: ISrpRefactorParameters,
        document: vscode.TextDocument,
        token: vscode.CancellationToken
    ): Promise<vscode.LanguageModelToolResult> {
        const maxLines = params.maxLinesPerModule || 50;
        const steps: SrpStep[] = [];
        const extractedModules: { module_name: string; module_path: string; symbols: string[] }[] = [];

        try {
            const analyzeStep: SrpStep = {
                step: 1,
                action: 'analyze',
                description: 'Analyzing Rust file symbols and structure',
                status: 'pending'
            };
            steps.push(analyzeStep);

            const lineCount = document.lineCount;
            const fileCode = document.getText();

            const analyzeResult = await this.analyzeTool.invoke({
                input: {
                    filePath: params.filePath,
                    startLine: 1,
                    endLine: lineCount
                }
            } as any, token);

            const part = analyzeResult.content[0] as any;
            const analysisText: string = part?.value ?? part?.toString() ?? '';
            const jsonMatch = analysisText.match(/```json\n([\s\S]*?)\n```/);
            if (!jsonMatch) {
                throw new Error('Failed to parse Rust analysis result');
            }
            const analysis = JSON.parse(jsonMatch[1]);

            analyzeStep.status = 'complete';
            analyzeStep.result = analysis;

            const planStep: SrpStep = {
                step: 2,
                action: 'plan',
                description: 'LLM planning SRP Rust module splits',
                status: 'pending'
            };
            steps.push(planStep);

            const plan = await this.llmPlanSrpSplit(
                'rust',
                fileCode,
                analysis,
                maxLines,
                params.targetDirectory,
                token
            );
            planStep.status = 'complete';
            planStep.result = plan;

            const workspaceRoot = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
            if (!workspaceRoot) {
                throw new Error('No workspace folder found');
            }

            const validationPaths = new Set<string>([params.filePath]);
            for (const group of plan.groups) {
                const targetPath = this.ensureLanguagePath(group.target_path, group.module_name, 'rust');
                const targetAbs = path.isAbsolute(targetPath) ? targetPath : path.join(workspaceRoot, targetPath);
                validationPaths.add(targetAbs);
            }
            const baselineDiagnostics = await this.collectErrorDiagnosticsSnapshot([...validationPaths]);

            let stepNum = 3;
            for (const group of plan.groups) {
                const extractStep: SrpStep = {
                    step: stepNum++,
                    action: 'extract',
                    description: `Extracting Rust group '${group.module_name}' (${group.symbols.length} symbols)`,
                    status: 'pending'
                };
                steps.push(extractStep);

                try {
                    const freshDoc = await vscode.workspace.openTextDocument(document.uri);
                    const freshLineCount = freshDoc.lineCount;

                    for (const symbolName of group.symbols) {
                        try {
                            await this.extractTool.invoke({
                                input: {
                                    sourceFilePath: params.filePath,
                                    startLine: 1,
                                    endLine: freshLineCount,
                                    functionName: symbolName,
                                    moduleName: group.module_name,
                                    modulePath: this.ensureLanguagePath(group.target_path, group.module_name, 'rust')
                                }
                            } as any, token);

                            logToOutput(`[SrpRefactor] Extracted Rust symbol '${symbolName}' → ${group.target_path}`);
                        } catch (symbolErr) {
                            logToOutput(`[SrpRefactor] Warning: Could not extract Rust symbol '${symbolName}': ${symbolErr}`);
                        }
                    }

                    extractStep.status = 'complete';
                    extractedModules.push({
                        module_name: group.module_name,
                        module_path: this.ensureLanguagePath(group.target_path, group.module_name, 'rust'),
                        symbols: group.symbols
                    });
                } catch (error) {
                    extractStep.status = 'failed';
                    extractStep.error = error instanceof Error ? error.message : String(error);
                }
            }

            const importStep: SrpStep = {
                step: stepNum++,
                action: 'import',
                description: 'Suggesting Rust missing imports',
                status: 'pending'
            };
            steps.push(importStep);

            const suggestedImports: { type_name: string; import_path: string; confidence: number }[] = [];
            if (params.autoFixImports !== false && analysis.dependencies?.used_types?.length > 0) {
                try {
                    const importJson = await suggestImportsForTypes(workspaceRoot, analysis.dependencies.used_types);
                    const matches = JSON.parse(importJson);

                    for (const m of matches) {
                        if (m.confidence > 0.5) {
                            suggestedImports.push({
                                type_name: m.item.name,
                                import_path: m.item.full_path,
                                confidence: m.confidence
                            });
                        }
                    }

                    importStep.status = 'complete';
                    importStep.result = suggestedImports;
                } catch (error) {
                    importStep.status = 'failed';
                    importStep.error = error instanceof Error ? error.message : String(error);
                }
            } else {
                importStep.status = 'complete';
            }

            const validateStep: SrpStep = {
                step: stepNum++,
                action: 'validate',
                description: 'Validating Rust refactor output with LSP diagnostics',
                status: 'pending'
            };
            steps.push(validateStep);

            try {
                const validation = await this.validateNoIntroducedErrors([...validationPaths], baselineDiagnostics);
                if (validation.introduced_error_count > 0) {
                    validateStep.status = 'failed';
                    validateStep.error = `Refactor introduced ${validation.introduced_error_count} new diagnostics error(s)`;
                    validateStep.result = validation;
                } else {
                    validateStep.status = 'complete';
                    validateStep.result = validation;
                }
            } catch (error) {
                validateStep.status = 'failed';
                validateStep.error = error instanceof Error ? error.message : String(error);
            }

            return this.buildResult(
                params.filePath,
                maxLines,
                steps,
                extractedModules,
                suggestedImports,
                plan.reasoning,
                'rust'
            );
        } catch (error) {
            const msg = error instanceof Error ? error.message : String(error);
            return new vscode.LanguageModelToolResult([
                new vscode.LanguageModelTextPart(`❌ SRP Rust refactor failed: ${msg}`)
            ]);
        }
    }

    // ========================================================================
    // TypeScript flow (new)
    // ========================================================================

    private async invokeTypeScript(
        params: ISrpRefactorParameters,
        document: vscode.TextDocument,
        token: vscode.CancellationToken
    ): Promise<vscode.LanguageModelToolResult> {
        const maxLines = params.maxLinesPerModule || 50;
        const tsExtension = document.languageId === 'typescriptreact' ? '.tsx' : '.ts';
        const steps: SrpStep[] = [];
        const extractedModules: { module_name: string; module_path: string; symbols: string[] }[] = [];

        try {
            const analyzeStep: SrpStep = {
                step: 1,
                action: 'analyze',
                description: 'Analyzing TypeScript symbols and structure',
                status: 'pending'
            };
            steps.push(analyzeStep);

            const fileCode = document.getText();
            const analysis = await this.analyzeTypeScriptDocument(document);
            analyzeStep.status = 'complete';
            analyzeStep.result = analysis;

            const planStep: SrpStep = {
                step: 2,
                action: 'plan',
                description: 'LLM planning SRP TypeScript module splits',
                status: 'pending'
            };
            steps.push(planStep);

            const defaultBase = params.targetDirectory || this.inferTypeScriptBaseDir(document.uri.fsPath);
            const plan = await this.llmPlanSrpSplit(
                'typescript',
                fileCode,
                analysis,
                maxLines,
                defaultBase,
                token
            );
            planStep.status = 'complete';
            planStep.result = plan;

            let stepNum = 3;
            const exportsToAdd = new Set<string>();
            const movedRanges: vscode.Range[] = [];
            const movedSymbolNames = new Set<string>();
            const symbolMap = new Map<string, TsTopLevelSymbol>();
            for (const s of analysis.ts_symbols as TsTopLevelSymbol[]) {
                if (!symbolMap.has(s.name)) {
                    symbolMap.set(s.name, s);
                }
            }

            const sourceText = document.getText();
            const sourceImports = this.extractTypeScriptImports(sourceText);
            const workspaceRoot = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
            if (!workspaceRoot) {
                throw new Error('No workspace folder found');
            }

            const validationPaths = new Set<string>([document.uri.fsPath]);
            for (const group of plan.groups) {
                const targetPath = this.ensureTypeScriptPath(group.target_path, group.module_name, tsExtension);
                const targetAbs = path.isAbsolute(targetPath)
                    ? targetPath
                    : path.join(workspaceRoot, targetPath);
                validationPaths.add(targetAbs);
            }
            const baselineDiagnostics = await this.collectErrorDiagnosticsSnapshot([...validationPaths]);
            const fileSnapshots = await this.snapshotFiles([...validationPaths]);

            for (const group of plan.groups) {
                const extractStep: SrpStep = {
                    step: stepNum++,
                    action: 'extract',
                    description: `Extracting TypeScript group '${group.module_name}' (${group.symbols.length} symbols)`,
                    status: 'pending'
                };
                steps.push(extractStep);

                try {
                    const targetPath = this.ensureTypeScriptPath(group.target_path, group.module_name, tsExtension);
                    const targetAbs = path.isAbsolute(targetPath)
                        ? targetPath
                        : path.join(workspaceRoot, targetPath);
                    validationPaths.add(targetAbs);

                    if (targetAbs === document.uri.fsPath) {
                        throw new Error(`Refusing to extract TypeScript group '${group.module_name}' over the source file`);
                    }

                    const selection = this.resolveTypeScriptGroupSymbols(group.symbols, symbolMap);
                    const selectedSymbols: TsTopLevelSymbol[] = [];
                    const duplicateSymbols: string[] = [];
                    for (const sym of selection.matched) {
                        if (movedSymbolNames.has(sym.name)) {
                            duplicateSymbols.push(sym.name);
                            continue;
                        }
                        selectedSymbols.push(sym);
                        movedSymbolNames.add(sym.name);
                        movedRanges.push(sym.range);
                    }

                    if (selection.unmatched.length > 0 || duplicateSymbols.length > 0) {
                        logToOutput(
                            `[SrpRefactor] TS group '${group.module_name}' unresolved symbols: ` +
                            `${selection.unmatched.join(', ') || 'none'}; duplicates skipped: ${duplicateSymbols.join(', ') || 'none'}`
                        );
                    }

                    if (selectedSymbols.length === 0) {
                        extractStep.status = 'failed';
                        const unresolved = [...selection.unmatched, ...duplicateSymbols];
                        extractStep.error = unresolved.length > 0
                            ? `No matching symbols found in source document for this group (planned: ${group.symbols.join(', ')}, unresolved: ${unresolved.join(', ')})`
                            : 'No matching symbols found in source document for this group';
                        continue;
                    }

                    const moduleBody = selectedSymbols
                        .map(s => this.ensureExportedTypeScriptDeclaration(s.text.trim()))
                        .join('\n\n');
                    const moduleHeader = `// Auto-generated by Rusty Refactor (SRP)\n// Responsibility: ${group.responsibility}`;
                    const importBlock = sourceImports.length > 0
                        ? this.rewriteTypeScriptImportsForTarget(sourceImports, path.dirname(document.uri.fsPath), path.dirname(targetAbs)).join('\n')
                        : '';
                    const moduleContent = [moduleHeader, importBlock, moduleBody]
                        .filter(Boolean)
                        .join('\n\n') + '\n';

                    await vscode.workspace.fs.createDirectory(vscode.Uri.file(path.dirname(targetAbs)));
                    await vscode.workspace.fs.writeFile(vscode.Uri.file(targetAbs), Buffer.from(moduleContent, 'utf8'));

                    const relNoExt = this.toRelativeImportPath(path.dirname(document.uri.fsPath), targetAbs, tsExtension);
                    exportsToAdd.add(`export * from '${relNoExt}';`);

                    extractStep.status = 'complete';
                    extractStep.result = {
                        matched_symbols: selectedSymbols.map(s => s.name),
                        unresolved_symbols: selection.unmatched,
                        duplicate_symbols_skipped: duplicateSymbols
                    };
                    extractedModules.push({
                        module_name: group.module_name,
                        module_path: targetPath,
                        symbols: selectedSymbols.map(s => s.name)
                    });
                } catch (error) {
                    extractStep.status = 'failed';
                    extractStep.error = error instanceof Error ? error.message : String(error);
                }
            }

            // Remove moved declarations from original source (bottom-up to avoid range shifts)
            if (movedRanges.length > 0) {
                const edit = new vscode.WorkspaceEdit();
                const sorted = [...movedRanges].sort((a, b) => {
                    if (a.start.line !== b.start.line) {
                        return b.start.line - a.start.line;
                    }
                    return b.start.character - a.start.character;
                });

                for (const range of sorted) {
                    edit.replace(document.uri, range, '');
                }

                await vscode.workspace.applyEdit(edit);
                await document.save();
            }

            const importStep: SrpStep = {
                step: stepNum++,
                action: 'import',
                description: 'Updating TypeScript exports in source file',
                status: 'pending'
            };
            steps.push(importStep);

            // Add imports for moved symbols plus export barrel lines at end of source file.
            try {
                const refreshed = await vscode.workspace.openTextDocument(document.uri);
                const existing = refreshed.getText();
                const localImports = this.buildSourceImportsForMovedTypeScriptSymbols(
                    existing,
                    path.dirname(document.uri.fsPath),
                    extractedModules.map(m => ({
                        modulePath: path.isAbsolute(m.module_path) ? m.module_path : path.join(workspaceRoot, m.module_path),
                        symbols: m.symbols
                    })),
                    tsExtension
                ).filter(i => !existing.includes(i));
                const missingExports = [...exportsToAdd].filter(e => !existing.includes(e));
                if (localImports.length > 0 || missingExports.length > 0) {
                    const addEdit = new vscode.WorkspaceEdit();
                    if (localImports.length > 0) {
                        const insertPos = this.getTypeScriptImportInsertPosition(refreshed);
                        addEdit.insert(refreshed.uri, insertPos, `${localImports.join('\n')}\n`);
                    }
                    if (missingExports.length > 0) {
                        const insertPos = new vscode.Position(refreshed.lineCount, 0);
                        addEdit.insert(refreshed.uri, insertPos, `\n${missingExports.join('\n')}\n`);
                    }
                    await vscode.workspace.applyEdit(addEdit);
                    await refreshed.save();
                }

                importStep.status = 'complete';
                importStep.result = { imports_added: localImports.length, exports_added: missingExports.length };
            } catch (error) {
                importStep.status = 'failed';
                importStep.error = error instanceof Error ? error.message : String(error);
            }

            const validateStep: SrpStep = {
                step: stepNum++,
                action: 'validate',
                description: 'Validating TypeScript refactor output with LSP diagnostics',
                status: 'pending'
            };
            steps.push(validateStep);

            try {
                const validation = await this.validateNoIntroducedErrors([...validationPaths], baselineDiagnostics);
                if (validation.introduced_error_count > 0) {
                    await this.restoreFileSnapshots(fileSnapshots);
                    validateStep.status = 'failed';
                    validateStep.error = `Refactor introduced ${validation.introduced_error_count} new diagnostics error(s); all TypeScript edits were rolled back`;
                    validateStep.result = { ...validation, rolled_back: true };
                    extractedModules.length = 0;
                } else {
                    validateStep.status = 'complete';
                    validateStep.result = validation;
                }
            } catch (error) {
                validateStep.status = 'failed';
                validateStep.error = error instanceof Error ? error.message : String(error);
            }

            return this.buildResult(
                params.filePath,
                maxLines,
                steps,
                extractedModules,
                [],
                plan.reasoning,
                'typescript'
            );
        } catch (error) {
            const msg = error instanceof Error ? error.message : String(error);
            return new vscode.LanguageModelToolResult([
                new vscode.LanguageModelTextPart(`❌ SRP TypeScript refactor failed: ${msg}`)
            ]);
        }
    }

    private resolveTypeScriptGroupSymbols(
        plannedSymbols: string[],
        symbolMap: Map<string, TsTopLevelSymbol>
    ): { matched: TsTopLevelSymbol[]; unmatched: string[] } {
        const matched: TsTopLevelSymbol[] = [];
        const unmatched: string[] = [];
        const seen = new Set<string>();

        const lowerNameMap = new Map<string, TsTopLevelSymbol>();
        const canonicalNameMap = new Map<string, TsTopLevelSymbol>();
        for (const sym of symbolMap.values()) {
            lowerNameMap.set(sym.name.toLowerCase(), sym);
            canonicalNameMap.set(this.symbolCanonicalKey(sym.name), sym);
        }

        for (const raw of plannedSymbols) {
            const normalized = this.normalizePlannedTypeScriptSymbolName(raw);
            const candidates = [raw.trim(), normalized].filter(Boolean);

            let resolved: TsTopLevelSymbol | undefined;
            for (const candidate of candidates) {
                resolved = symbolMap.get(candidate)
                    || lowerNameMap.get(candidate.toLowerCase())
                    || canonicalNameMap.get(this.symbolCanonicalKey(candidate));
                if (resolved) {
                    break;
                }
            }

            if (resolved) {
                if (!seen.has(resolved.name)) {
                    matched.push(resolved);
                    seen.add(resolved.name);
                }
            } else {
                unmatched.push(raw);
            }
        }

        return { matched, unmatched };
    }

    private normalizePlannedTypeScriptSymbolName(raw: string): string {
        const withoutParens = raw.replace(/\([^)]*\)/g, ' ');
        const withoutKindPrefix = withoutParens.replace(
            /^\s*(class|interface|enum|type|function|const|let|var|module|namespace)\s+/i,
            ''
        );
        const tokens = withoutKindPrefix.match(/[A-Za-z_$][A-Za-z0-9_$]*/g) || [];
        const noiseWords = new Set([
            'class', 'interface', 'enum', 'type', 'function', 'const', 'let', 'var',
            'module', 'namespace', 'line', 'lines', 'symbol', 'symbols'
        ]);

        for (let i = tokens.length - 1; i >= 0; i--) {
            const token = tokens[i];
            if (!noiseWords.has(token.toLowerCase())) {
                return token;
            }
        }

        return raw.trim();
    }

    private symbolCanonicalKey(name: string): string {
        return name.replace(/[^A-Za-z0-9_$]/g, '').toLowerCase();
    }

    private async analyzeTypeScriptDocument(document: vscode.TextDocument): Promise<any> {
        const symbols = await vscode.commands.executeCommand<vscode.DocumentSymbol[]>(
            'vscode.executeDocumentSymbolProvider',
            document.uri
        ) || [];

        const top = symbols.filter(s => this.isTopLevelTypeScriptSymbol(s.kind));
        const tsSymbols: TsTopLevelSymbol[] = top.map(s => ({
            name: s.name,
            kind: this.symbolKindName(s.kind),
            range: s.range,
            text: document.getText(s.range)
        }));

        const functions = top
            .filter(s => s.kind === vscode.SymbolKind.Function)
            .map(s => ({ name: s.name, visibility: 'public', has_generics: document.getText(s.range).includes('<') }));

        const structs = top
            .filter(s => s.kind === vscode.SymbolKind.Class)
            .map(s => ({
                name: s.name,
                visibility: 'public',
                field_count: s.children.filter(c => c.kind === vscode.SymbolKind.Property || c.kind === vscode.SymbolKind.Field).length,
                has_generics: document.getText(s.range).includes('<')
            }));

        const enums = top
            .filter(s => s.kind === vscode.SymbolKind.Enum)
            .map(s => ({
                name: s.name,
                visibility: 'public',
                variant_count: s.children.length,
                has_generics: false
            }));

        const traits = top
            .filter(s => s.kind === vscode.SymbolKind.Interface)
            .map(s => ({ name: s.name, isPublic: true, hasGenerics: document.getText(s.range).includes('<') }));

        const implementations = top
            .filter(s => s.kind === vscode.SymbolKind.Class)
            .map(s => ({
                target: s.name,
                trait: null,
                method_count: s.children.filter(c => c.kind === vscode.SymbolKind.Method).length
            }));

        return {
            file: path.basename(document.uri.fsPath),
            lines: { start: 1, end: document.lineCount },
            functions,
            structs,
            enums,
            traits,
            implementations,
            dependencies: {
                used_types: [],
                used_traits: [],
                imports: this.extractTypeScriptImports(document.getText())
            },
            ts_symbols: tsSymbols,
            extractable: tsSymbols.length > 0
        };
    }

    private extractTypeScriptImports(text: string): string[] {
        const imports: string[] = [];
        const lines = text.split(/\r?\n/);
        for (let i = 0; i < lines.length; i++) {
            const firstLine = lines[i].trim();
            if (!/^import(?:\s|\{|\*)/i.test(firstLine)) {
                continue;
            }

            let statement = lines[i];
            while (!statement.trim().endsWith(';') && i + 1 < lines.length) {
                i++;
                statement += `\n${lines[i]}`;
            }

            imports.push(statement.trim());
        }
        return imports;
    }

    private ensureExportedTypeScriptDeclaration(text: string): string {
        if (/^export\s+/m.test(text)) {
            return text;
        }

        if (/^declare\s+/m.test(text)) {
            return text.replace(/^declare\s+/, 'export declare ');
        }

        return text.replace(
            /^(async\s+function|function|class|interface|enum|type|namespace|module|const|let|var)\b/m,
            'export $1'
        );
    }

    private rewriteTypeScriptImportsForTarget(imports: string[], sourceDir: string, targetDir: string): string[] {
        return imports.map(importStatement => {
            const moduleSpecifier = this.getTypeScriptModuleSpecifier(importStatement);
            if (!moduleSpecifier || !moduleSpecifier.startsWith('.')) {
                return importStatement;
            }

            const absoluteImport = path.resolve(sourceDir, moduleSpecifier);
            const rewritten = this.toRelativeImportPath(targetDir, absoluteImport, path.extname(absoluteImport) as '.ts' | '.tsx' | '.rs');
            return importStatement.replace(
                /from\s+(['"])([^'"]+)\1|import\s*\(\s*(['"])([^'"]+)\3\s*\)/,
                match => match.replace(moduleSpecifier, rewritten)
            );
        });
    }

    private getTypeScriptModuleSpecifier(importStatement: string): string | undefined {
        const fromMatch = importStatement.match(/from\s+['"]([^'"]+)['"]/);
        if (fromMatch) {
            return fromMatch[1];
        }

        const sideEffectMatch = importStatement.match(/^\s*import\s+['"]([^'"]+)['"]/);
        return sideEffectMatch?.[1];
    }

    private buildSourceImportsForMovedTypeScriptSymbols(
        currentSourceText: string,
        sourceDir: string,
        modules: { modulePath: string; symbols: string[] }[],
        extToStrip: '.ts' | '.tsx'
    ): string[] {
        const existingImports = this.extractTypeScriptImports(currentSourceText).join('\n');
        const imports: string[] = [];

        for (const mod of modules) {
            const usedSymbols = mod.symbols.filter(symbol => this.hasIdentifierUseOutsideImports(currentSourceText, symbol));
            if (usedSymbols.length === 0) {
                continue;
            }

            const importPath = this.toRelativeImportPath(sourceDir, mod.modulePath, extToStrip);
            const statement = `import { ${usedSymbols.join(', ')} } from '${importPath}';`;
            if (!existingImports.includes(`from '${importPath}'`) && !existingImports.includes(`from \"${importPath}\"`)) {
                imports.push(statement);
            }
        }

        return imports;
    }

    private hasIdentifierUseOutsideImports(text: string, identifier: string): boolean {
        const withoutImports = text
            .split(/\r?\n/)
            .filter(line => !/^\s*import\b/.test(line.trim()))
            .join('\n');
        const escaped = identifier.replace(/[-/\^$*+?.()|[\]{}]/g, '\$&');
        return new RegExp(`\b${escaped}\b`).test(withoutImports);
    }

    private getTypeScriptImportInsertPosition(document: vscode.TextDocument): vscode.Position {
        let insertLine = 0;
        for (let i = 0; i < document.lineCount; i++) {
            const line = document.lineAt(i).text.trim();
            if (line.length === 0 || line.startsWith('//') || line.startsWith('/*') || line.startsWith('*')) {
                insertLine = i + 1;
                continue;
            }
            if (/^import\b/.test(line)) {
                insertLine = i + 1;
                continue;
            }
            break;
        }
        return new vscode.Position(insertLine, 0);
    }

    private async snapshotFiles(filePaths: string[]): Promise<Map<string, Uint8Array | undefined>> {
        const snapshots = new Map<string, Uint8Array | undefined>();
        for (const filePath of [...new Set(filePaths.map(p => path.resolve(p)))]) {
            const uri = vscode.Uri.file(filePath);
            try {
                snapshots.set(filePath, await vscode.workspace.fs.readFile(uri));
            } catch {
                snapshots.set(filePath, undefined);
            }
        }
        return snapshots;
    }

    private async restoreFileSnapshots(snapshots: Map<string, Uint8Array | undefined>): Promise<void> {
        for (const [filePath, contents] of snapshots.entries()) {
            const uri = vscode.Uri.file(filePath);
            if (contents) {
                await vscode.workspace.fs.createDirectory(vscode.Uri.file(path.dirname(filePath)));
                await vscode.workspace.fs.writeFile(uri, contents);
            } else {
                try {
                    await vscode.workspace.fs.delete(uri);
                } catch {
                    // File did not exist before the refactor and is already gone.
                }
            }
        }
    }

    private isTopLevelTypeScriptSymbol(kind: vscode.SymbolKind): boolean {
        return [
            vscode.SymbolKind.Class,
            vscode.SymbolKind.Enum,
            vscode.SymbolKind.Function,
            vscode.SymbolKind.Interface,
            vscode.SymbolKind.Variable,
            vscode.SymbolKind.Constant,
            vscode.SymbolKind.Namespace,
            vscode.SymbolKind.Module,
            vscode.SymbolKind.TypeParameter
        ].includes(kind);
    }

    private symbolKindName(kind: vscode.SymbolKind): string {
        const map: Record<number, string> = {
            [vscode.SymbolKind.Class]: 'class',
            [vscode.SymbolKind.Enum]: 'enum',
            [vscode.SymbolKind.Function]: 'function',
            [vscode.SymbolKind.Interface]: 'interface',
            [vscode.SymbolKind.Variable]: 'variable',
            [vscode.SymbolKind.Constant]: 'constant',
            [vscode.SymbolKind.Namespace]: 'namespace',
            [vscode.SymbolKind.Module]: 'module',
            [vscode.SymbolKind.TypeParameter]: 'type'
        };
        return map[kind] || 'symbol';
    }

    // ========================================================================
    // Planning
    // ========================================================================

    private async llmPlanSrpSplit(
        language: 'rust' | 'typescript',
        fileCode: string,
        analysis: any,
        maxLines: number,
        targetDir: string | undefined,
        _token: vscode.CancellationToken
    ): Promise<SrpPlan> {
        const estimatedInputTokens = Math.max(
            4000,
            Math.ceil((fileCode.length + JSON.stringify(analysis).length + 2000) / 4)
        );
        const symbolSummary = this.buildSymbolSummary(analysis, language);
        const baseDir = targetDir || this.inferBaseDir(analysis, language);
        const ext = language === 'rust' ? 'rs' : 'ts';
        const langPrompt = language === 'rust' ? 'Rust' : 'TypeScript';

        const systemPrompt = `You are a ${langPrompt} architecture expert. Group top-level symbols into cohesive modules following SRP.

RULES:
1. Each group is ONE module file and should be ≤${maxLines} non-blank lines.
2. Keep strongly-related symbols together.
3. module_name must be snake_case.
4. target_path pattern: "${baseDir}/{module_name}/{module_name}.${ext}".
5. Every symbol from input should appear exactly once.
6. Favor high cohesion and low coupling.
7. In "symbols", use EXACT symbol names from input only (e.g., "SrpPlan"), never prefixed forms like "INTERFACE SrpPlan".

Return ONLY valid JSON:
{
  "groups": [
    {
      "group_name": "Readable name",
      "module_name": "snake_case_name",
      "responsibility": "Single responsibility sentence",
      "symbols": ["SymbolA", "helperFn"],
      "target_path": "${baseDir}/snake_case_name/snake_case_name.${ext}"
    }
  ],
  "shared_imports": ["example import"],
  "reasoning": "brief split rationale"
}
No markdown fences, raw JSON only.`;

        const userPrompt = `SYMBOLS:\n${symbolSummary}\n\nFULL CODE:\n${fileCode}`;

        let planText: string;

        try {
            // Check if using custom endpoint (codetether)
            if (this.modelClient.shouldUseCustomEndpoint()) {
                logToOutput(`[SrpRefactor] Using custom model endpoint for planning`);
                const messages: ChatMessage[] = [
                    { role: 'system', content: systemPrompt },
                    { role: 'user', content: userPrompt }
                ];
                planText = await this.modelClient.sendChat(messages, {
                    justification: `Planning SRP module splits for ${langPrompt} file`,
                    token: _token
                });
            } else {
                // Use VS Code's built-in Language Model API
                const model = await this.selectPlanningModel(estimatedInputTokens);
                if (!model) {
                    logToOutput(`[SrpRefactor] No model available, using fallback plan`);
                    return this.fallbackPlan(analysis, targetDir, language);
                }

                const messages = [
                    vscode.LanguageModelChatMessage.User(`${systemPrompt}\n\n${userPrompt}`)
                ];

                const response = await model.sendRequest(
                    messages,
                    { justification: `Planning SRP module splits for ${langPrompt} file` },
                    _token
                );

                planText = '';
                for await (const fragment of response.text) {
                    planText += fragment;
                }
            }

            planText = planText.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();

            const plan: SrpPlan = JSON.parse(planText);
            if (!plan.groups || !Array.isArray(plan.groups) || plan.groups.length === 0) {
                throw new Error('Plan has no groups');
            }

            for (const g of plan.groups) {
                if (!g.module_name || !g.symbols || g.symbols.length === 0) {
                    throw new Error(`Invalid group: ${g.group_name || 'unnamed'}`);
                }
                g.module_name = Utils.toSnakeCase(g.module_name).replace(/^_/, '');
                g.target_path = this.ensureLanguagePath(g.target_path, g.module_name, language);
            }

            return plan;
        } catch (parseErr) {
            logToOutput(`[SrpRefactor] LLM plan parse failed: ${parseErr}. Using fallback plan.`);
            return this.fallbackPlan(analysis, targetDir, language);
        }
    }

    private fallbackPlan(analysis: any, targetDir: string | undefined, language: 'rust' | 'typescript'): SrpPlan {
        const baseDir = targetDir || this.inferBaseDir(analysis, language);
        const ext = language === 'rust' ? 'rs' : 'ts';
        const groups: SrpGroup[] = [];
        const seen = new Set<string>();

        if (language === 'typescript' && Array.isArray(analysis.ts_symbols)) {
            for (const symbol of analysis.ts_symbols as TsTopLevelSymbol[]) {
                if (seen.has(symbol.name)) continue;
                const moduleName = Utils.toSnakeCase(symbol.name).replace(/^_/, '');
                seen.add(symbol.name);
                groups.push({
                    group_name: symbol.name,
                    module_name: moduleName,
                    responsibility: `${symbol.kind} ${symbol.name}`,
                    symbols: [symbol.name],
                    target_path: `${baseDir}/${moduleName}/${moduleName}.${ext}`
                });
            }

            return {
                groups,
                shared_imports: analysis.dependencies?.imports || [],
                reasoning: 'Fallback plan (TypeScript): one module per top-level symbol'
            };
        }

        // Rust fallback
        for (const s of (analysis.structs || [])) {
            const moduleName = Utils.toSnakeCase(s.name).replace(/^_/, '');
            const symbolName = s.name;
            if (seen.has(symbolName)) continue;
            seen.add(symbolName);
            groups.push({
                group_name: s.name,
                module_name: moduleName,
                responsibility: `${s.name} data structure and methods`,
                symbols: [symbolName],
                target_path: `${baseDir}/${moduleName}/${moduleName}.${ext}`
            });
        }

        for (const e of (analysis.enums || [])) {
            if (seen.has(e.name)) continue;
            const moduleName = Utils.toSnakeCase(e.name).replace(/^_/, '');
            seen.add(e.name);
            groups.push({
                group_name: e.name,
                module_name: moduleName,
                responsibility: `${e.name} enum and related logic`,
                symbols: [e.name],
                target_path: `${baseDir}/${moduleName}/${moduleName}.${ext}`
            });
        }

        for (const t of (analysis.traits || [])) {
            const name = typeof t === 'string' ? t : t.name;
            if (seen.has(name)) continue;
            const moduleName = Utils.toSnakeCase(name).replace(/^_/, '');
            seen.add(name);
            groups.push({
                group_name: name,
                module_name: moduleName,
                responsibility: `${name} trait definition`,
                symbols: [name],
                target_path: `${baseDir}/${moduleName}/${moduleName}.${ext}`
            });
        }

        for (const f of (analysis.functions || [])) {
            if (seen.has(f.name)) continue;
            const moduleName = Utils.toSnakeCase(f.name).replace(/^_/, '');
            seen.add(f.name);
            groups.push({
                group_name: f.name,
                module_name: moduleName,
                responsibility: `${f.name} function`,
                symbols: [f.name],
                target_path: `${baseDir}/${moduleName}/${moduleName}.${ext}`
            });
        }

        return {
            groups,
            shared_imports: analysis.dependencies?.imports || [],
            reasoning: 'Fallback plan (Rust): one module per top-level symbol'
        };
    }

    // ========================================================================
    // Shared helpers
    // ========================================================================

    private async collectErrorDiagnosticsSnapshot(filePaths: string[]): Promise<Map<string, Set<string>>> {
        const uniqueFilePaths = [...new Set(filePaths.map(p => path.resolve(p)))];
        const uris = uniqueFilePaths.map(p => vscode.Uri.file(p));

        for (const uri of uris) {
            try {
                await vscode.workspace.openTextDocument(uri);
            } catch {
                // Ignore files that do not exist yet
            }
        }

        await this.waitForDiagnosticsSettle(uris);

        const snapshot = new Map<string, Set<string>>();
        for (const uri of uris) {
            const errors = vscode.languages
                .getDiagnostics(uri)
                .filter(d => d.severity === vscode.DiagnosticSeverity.Error)
                .map(d => this.diagnosticKey(d));

            snapshot.set(this.normalizeFileKey(uri.fsPath), new Set(errors));
        }

        return snapshot;
    }

    private async validateNoIntroducedErrors(
        filePaths: string[],
        baseline: Map<string, Set<string>>
    ): Promise<{
        checked_files: number;
        introduced_error_count: number;
        introduced_errors: { file_path: string; diagnostic: string }[];
    }> {
        const uniqueFilePaths = [...new Set(filePaths.map(p => path.resolve(p)))];
        const filePathByKey = new Map<string, string>();
        for (const filePath of uniqueFilePaths) {
            filePathByKey.set(this.normalizeFileKey(filePath), filePath);
        }

        const current = await this.collectErrorDiagnosticsSnapshot(uniqueFilePaths);
        const introducedErrors: { file_path: string; diagnostic: string }[] = [];

        for (const [fileKey, currentErrors] of current.entries()) {
            const baselineErrors = baseline.get(fileKey) || new Set<string>();
            for (const diagnostic of currentErrors) {
                if (!baselineErrors.has(diagnostic)) {
                    introducedErrors.push({
                        file_path: filePathByKey.get(fileKey) || fileKey,
                        diagnostic
                    });
                }
            }
        }

        return {
            checked_files: uniqueFilePaths.length,
            introduced_error_count: introducedErrors.length,
            introduced_errors: introducedErrors.slice(0, 25)
        };
    }

    private async waitForDiagnosticsSettle(uris: vscode.Uri[]): Promise<void> {
        const config = vscode.workspace.getConfiguration('rustyRefactor');
        const timeoutMs = Math.max(1000, config.get<number>('rustAnalyzerValidationTimeoutMs', 5000));
        const pollIntervalMs = Math.max(100, config.get<number>('rustAnalyzerValidationPollIntervalMs', 200));

        const start = Date.now();
        let stableIterations = 0;
        let lastSignature = '';

        while (Date.now() - start < timeoutMs) {
            const signature = this.diagnosticsSignature(uris);
            if (signature === lastSignature) {
                stableIterations++;
                if (stableIterations >= 2) {
                    return;
                }
            } else {
                stableIterations = 0;
                lastSignature = signature;
            }

            await new Promise(resolve => setTimeout(resolve, pollIntervalMs));
        }
    }

    private diagnosticsSignature(uris: vscode.Uri[]): string {
        const parts: string[] = [];

        for (const uri of uris) {
            const diagnostics = vscode.languages
                .getDiagnostics(uri)
                .filter(d => d.severity === vscode.DiagnosticSeverity.Error)
                .map(d => this.diagnosticKey(d))
                .sort();

            parts.push(`${this.normalizeFileKey(uri.fsPath)}:${diagnostics.join('|')}`);
        }

        return parts.sort().join('||');
    }

    private normalizeFileKey(filePath: string): string {
        return path.resolve(filePath).replace(/\\/g, '/').toLowerCase();
    }

    private diagnosticKey(diagnostic: vscode.Diagnostic): string {
        const code = typeof diagnostic.code === 'object'
            ? (diagnostic.code.value ?? '')
            : (diagnostic.code ?? '');

        return `${diagnostic.source || ''}|${String(code)}|${diagnostic.message}`.trim();
    }

    private ensureLanguagePath(rawPath: string | undefined, moduleName: string, language: 'rust' | 'typescript'): string {
        const ext = language === 'rust' ? '.rs' : '.ts';
        if (!rawPath || rawPath.trim().length === 0) {
            const base = language === 'rust' ? 'src/utils' : 'src/modules';
            return language === 'rust' ? `${base}/${moduleName}.rs` : `${base}/${moduleName}.ts`;
        }

        let p = rawPath.replace(/\\/g, '/');
        if (!p.endsWith(ext)) {
            p = p.replace(/\.[a-zA-Z0-9]+$/, '') + ext;
        }
        
        // Remove duplicate folder/file names, e.g. src/modules/foo/foo.ts -> src/modules/foo.ts
        const parts = p.split('/');
        if (parts.length >= 2) {
            const last = parts[parts.length - 1];
            const secondToLast = parts[parts.length - 2];
            const lastNoExt = last.slice(0, -ext.length);
            if (lastNoExt === secondToLast) {
                parts.splice(parts.length - 2, 1);
                p = parts.join('/');
            }
        }
        return p;
    }


    private ensureTypeScriptPath(rawPath: string | undefined, moduleName: string, ext: '.ts' | '.tsx'): string {
        const normalized = this.ensureLanguagePath(rawPath, moduleName, 'typescript');
        return ext === '.tsx' ? normalized.replace(/\.ts$/, '.tsx') : normalized;
    }

    private buildSymbolSummary(analysis: any, language: 'rust' | 'typescript'): string {
        const lines: string[] = [];

        if (language === 'typescript' && Array.isArray(analysis.ts_symbols)) {
            for (const s of analysis.ts_symbols as TsTopLevelSymbol[]) {
                const lineCount = s.range.end.line - s.range.start.line + 1;
                lines.push(`${s.kind.toUpperCase()} ${s.name} (${lineCount} lines)`);
            }
            return lines.join('\n');
        }

        for (const s of (analysis.structs || [])) {
            lines.push(`STRUCT ${s.name} (${s.visibility}, ${s.field_count} fields${s.has_generics ? ', generic' : ''})`);
        }
        for (const e of (analysis.enums || [])) {
            lines.push(`ENUM ${e.name} (${e.visibility}, ${e.variant_count} variants)`);
        }
        for (const t of (analysis.traits || [])) {
            const name = typeof t === 'string' ? t : t.name;
            lines.push(`TRAIT ${name}`);
        }
        for (const f of (analysis.functions || [])) {
            lines.push(`FN ${f.name} (${f.visibility}${f.has_generics ? ', generic' : ''})`);
        }
        for (const impl of (analysis.implementations || [])) {
            const traitInfo = impl.trait ? ` for trait ${impl.trait}` : '';
            lines.push(`IMPL ${impl.target}${traitInfo} (${impl.method_count} methods)`);
        }

        return lines.join('\n');
    }

    private inferBaseDir(analysis: any, language: 'rust' | 'typescript'): string {
        if (language === 'typescript') {
            return 'src/modules';
        }

        const hasStructs = (analysis.structs?.length || 0) > 0;
        const hasTraits = (analysis.traits?.length || 0) > 0;
        const hasFunctions = (analysis.functions?.length || 0) > 0;
        const hasImpls = (analysis.implementations?.length || 0) > 0;

        if (hasImpls && hasFunctions && !hasStructs) {
            return 'src/services';
        }
        if (hasStructs) {
            return 'src/models';
        }
        if (hasTraits) {
            return 'src/traits';
        }
        return 'src/utils';
    }

    private inferTypeScriptBaseDir(sourceFilePath: string): string {
        const workspaceRoot = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
        if (!workspaceRoot) {
            return 'src/modules';
        }

        const sourceDir = path.dirname(sourceFilePath);
        const relativeDir = path.relative(workspaceRoot, sourceDir).replace(/\\/g, '/');
        return relativeDir.length > 0 ? `${relativeDir}/modules` : 'src/modules';
    }

    private toRelativeImportPath(fromDir: string, targetFileAbs: string, extToStrip: '.ts' | '.tsx' | '.rs'): string {
        let rel = path.relative(fromDir, targetFileAbs).replace(/\\/g, '/');
        if (rel.endsWith(extToStrip)) {
            rel = rel.slice(0, -extToStrip.length);
        }
        if (!rel.startsWith('.')) {
            rel = `./${rel}`;
        }
        return rel;
    }

    private isTypeScriptLanguage(languageId: string): boolean {
        return languageId === 'typescript' || languageId === 'typescriptreact';
    }

    private buildResult(
        filePath: string,
        maxLines: number,
        steps: SrpStep[],
        extractedModules: { module_name: string; module_path: string; symbols: string[] }[],
        suggestedImports: { type_name: string; import_path: string; confidence: number }[],
        reasoning: string,
        language: 'rust' | 'typescript'
    ): vscode.LanguageModelToolResult {
        const completed = steps.filter(s => s.status === 'complete').length;
        const failed = steps.filter(s => s.status === 'failed').length;

        let summary = failed === 0
            ? `✓ SRP ${language} refactor complete: ${completed}/${steps.length} steps successful`
            : `⚠ SRP ${language} refactor partial: ${completed}/${steps.length} steps successful, ${failed} failed`;

        summary += `\n\n**Constraint:** ≤${maxLines} lines per module`;
        summary += `\n**LLM reasoning:** ${reasoning}`;
        summary += `\n\n**Extracted Modules:**\n`;
        for (const mod of extractedModules) {
            summary += `- \`${mod.module_path}\`: ${mod.symbols.join(', ')}\n`;
        }

        if (suggestedImports.length > 0) {
            summary += `\n**Suggested Imports:**\n`;
            for (const imp of suggestedImports.slice(0, 5)) {
                summary += `- \`use ${imp.import_path};\` (${(imp.confidence * 100).toFixed(0)}%)\n`;
            }
        }

        const result = {
            success: failed === 0,
            language,
            file_path: filePath,
            max_lines_per_module: maxLines,
            total_steps: steps.length,
            completed_steps: completed,
            steps,
            extracted_modules: extractedModules,
            suggested_imports: suggestedImports,
            summary
        };

        return new vscode.LanguageModelToolResult([
            new vscode.LanguageModelTextPart(
                `${summary}\n\n**Full Result:**\n\`\`\`json\n${JSON.stringify(result, null, 2)}\n\`\`\``
            )
        ]);
    }

    private async selectPlanningModel(minInputTokens: number): Promise<vscode.LanguageModelChat | null> {
        try {
            const allModels = await vscode.lm.selectChatModels();
            if (allModels.length === 0) {
                return null;
            }

            const config = vscode.workspace.getConfiguration('rustyRefactor');
            const fastId = config.get<string>('aiFastModel');
            const preferredId = config.get<string>('aiPreferredModel');

            const matchById = (modelId: string | undefined): vscode.LanguageModelChat | undefined => {
                if (!modelId) {
                    return undefined;
                }
                return allModels.find(m => `${m.vendor}/${m.family}` === modelId);
            };

            const canHandle = (m: vscode.LanguageModelChat): boolean => m.maxInputTokens >= minInputTokens;

            const preferred = matchById(preferredId);
            if (preferred && canHandle(preferred)) {
                logToOutput(`[SrpRefactor] Using preferred model for planning: ${preferred.name}`);
                return preferred;
            }

            const fastModel = matchById(fastId);
            if (fastModel && canHandle(fastModel)) {
                logToOutput(`[SrpRefactor] Using configured fast model for planning: ${fastModel.name}`);
                return fastModel;
            }

            const fastFamilyRegex = /mini|flash|haiku|instant|fast|nano|small/i;
            const nonFastCandidates = allModels
                .filter(m => canHandle(m) && !fastFamilyRegex.test(m.family) && !fastFamilyRegex.test(m.name))
                .sort((a, b) => b.maxInputTokens - a.maxInputTokens);

            if (nonFastCandidates.length > 0) {
                logToOutput(`[SrpRefactor] Auto-selected quality planning model: ${nonFastCandidates[0].name}`);
                return nonFastCandidates[0];
            }

            const sorted = allModels
                .filter(canHandle)
                .sort((a, b) => b.maxInputTokens - a.maxInputTokens);

            if (sorted.length > 0) {
                logToOutput(`[SrpRefactor] Auto-selected model for planning: ${sorted[0].name}`);
                return sorted[0];
            }

            const largest = [...allModels].sort((a, b) => b.maxInputTokens - a.maxInputTokens)[0];
            logToOutput(`[SrpRefactor] Falling back to largest available planning model: ${largest.name}`);
            return largest;
        } catch {
            return null;
        }
    }
}
