[package]
name = "napi_bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.14", features = ["full"] }
napi-derive = "2.14"
anyhow = "1.0"

[build-dependencies]
napi-build = "2.1"
