name: Publish Extension (RustyRoad)

on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]
    branches: [ main ]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 0.2.6, auto, patch, minor, major)'
        required: false
        default: 'auto'
      prerelease:
        description: 'Publish as prerelease'
        required: false
        default: false
        type: boolean

jobs:
  publish:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}
      
    - name: 🦀 Publish with RustyRoad
      uses: ./.github/actions/rustyroad-publish
      with:
        version-bump: ${{ github.event.inputs.version || 'auto' }}
        prerelease: ${{ github.event.inputs.prerelease || 'false' }}
        vsce-pat: ${{ secrets.VSCE_PAT }}
        github-token: ${{ secrets.GH_TOKEN }}
        rust-version: 'stable'
        node-version: '20'
        cache-key-prefix: 'rusty-refactor-v1'
        create-github-release: 'true'
        skip-tests: 'true'
